### ISSUE TITLE
Blocks multi-cursor

### ISSUE THREAD

**Issue by Guest007** [vladimirnani/DjangoCommands#20]
Ctrl-button1 in Sublime used for multicoursor. DjangoCommands blocks this very important behavior

**Comment by Proyecto513** [comment]
"Ctrl+button1" is not "blocked" it's used inside the mouse map for "Django Click Command" as .mouse-map settings files do not support context, you can create in your User directory a "Default.mouse-map" file and override this setting

**Comment by Proyecto513** [comment]
I gave it a little thought and I realized that a pretty important thing about shortcuts on editors and IDE's is to keep hands away from mouse, of course is not always possible and multiselection is, IMHO, more important than opening a template.
