### ISSUE TITLE
DjangoCommands Interferes with highlighting when using CTRL+D (find_under_expand)

### ISSUE THREAD

**Issue by HackerLlama** [vladimirnani/DjangoCommands#22]
Normal behavior for CTRL+D (find_under_expand) is for the selection to be expanded, then for subsequent instances to be highlighted. When DjangoCommands is enabled, the function works properly, but the highlighting lags one step behind. This makes Sublime Text fairly impossible to use for those that are accustomed to having CTRL+D work as ususal.

Repro:
1. Download Sublime Text 3 Build 3083 x64 for Windows. Reproduces using full install and portable version.
2. Install package control.
3. Confirm normal operation: Create a new file with the same word repeated five times. Select the entire first instance, then press CTRL+D and see that the selection advances for each press.
4. Now install Django Manage Commands package with package control.
5. Confirm errant operation: Select the entire first instance again. Press CTRL+D and see that the first press has no visible effect. Press again and see the highlight appear for the previous press. Now press delete and see that one more instance was deleted than was highlighted.

**Comment by Proyecto513** [comment]
I made some tests, including the reproduction of yours and it seems to work just fine again
