### ISSUE TITLE
python_interpreter (project setting) not working or python_virtualenv_paths in Windows

### ISSUE THREAD

**Issue by ark4n631** [vladimirnani/DjangoCommands#23]
Took me hours to make it work on Windows, finally i got it working by putting the project \env\Scripts\python.exe in "python_bin" settings,
Doesn't works if i put "python_interpreter" in my project settings and doesn't works neither if put the virtualenv folder of the project in "python_virtualenv_paths" (tried that million ways with /, \ etc) none of that works, only if i put python_bin to project virtualenv python.exe works...

There is no documentation and how - to config after package control install... or file/project structure to follow (to make it works)

Hope you can explain or document better because looks good. But if it can't support virtualenv or per project settings can't give a good use

Regards and thanks a lot for your work!

**Comment by Proyecto513** [comment]
Will work on this inmediatly, I get your problem, the thing is that the  "python_virtualenv_paths" look for virtualenv folders inside the folders listed, and to use the project settings interpreter you have to set "use_project_interpreter" true, will document this better
