### ISSUE TITLE
Use parenthesis for python and manage.py paths when firing a command

### ISSUE THREAD

**Issue by nepi** [vladimirnani/DjangoCommands#25]
When the paths to either one of them contains a space the command fails. Putting it around parenthesis does the trick.

Example for django runserver command:
/path/to/with space/python /path/to/with space/mange.py runserver
vs.
"/path/to/with space/python" "/path/to/with space/mange.py" runserver

-> This line should get fixed: command = "{} {} {}".format(binary, self.manage_py, command)

Thanks for your great plugin!

**Comment by Proyecto513** [comment]
It's fixed now, thanks for your time reporting this issue
