### ISSUE TITLE
custom server command?

### ISSUE THREAD

**Issue by aarondiazr** [vladimirnani/DjangoCommands#31]
Hi!

I don't understand how to execute custom server command, i want to runserver command with custom setting args, for example:

`python manage.py runserver --settings=project.settings.dev`

Is possible?

**Comment by Proyecto513** [comment]
well yeah you just add:
`        "server_custom_command": 
        {
         "command": "manage.py",
         "args":
         [
             "runserver",
             "--settings=project.settings.dev",
         ]
        },`

to your project file and that must work
